### ISSUE TITLE
How have you generated pixel_pos_interpolate.csv ?  

### ISSUE THREAD

**Issue by AyeshaNirma** [vvanirudh/social-lstm-tf#11]
Hi Anirudh,

How have you normalized pixel_pos_interpolate ? I am sure its not normalized by width and height since there are negative values ? If its the generated by homography matrix please could you provide it or explain how have you generated it ? We need to plot the annotation on image.

P.S I know pixel_pos is normailzed by width and height

**Comment by vvanirudh** [comment]
It is similar to pixel_pos. Rather than normalizing it to lie between 0 and 1, the interpolate file normalizes it to lie between -1 and 1. 

And since each dataset had different frequency of annotation, I linearly interpolated between successive annotations to get positions at each frame. The pixel_pos_interpolate has these values.

**Comment by AyeshaNirma** [comment]
Perfect ! thank you

**Comment by erichhhhho** [comment]
Hi,
Could you tell me why between -1 to 1 instead of 0 to 1, please?
