### ISSUE TITLE
Is this the official implementation of ALahi et al workof CVPR' 16

### ISSUE THREAD

**Issue by AyeshaNirma** [vvanirudh/social-lstm-tf#9]
Hi

I just want to confirm is this the official implementation of the work ?
"Social LSTM: Human Trajectory Prediction in Crowded Spaces"

In the read me as well its not specified and you are not in the author list either so just wanted to confirm. 

Secondly, is it possible for you to share the trained model ? through dropbox etc ? 

Thanks

**Comment by vvanirudh** [comment]
This is not the official implementation of the work as the original authors have not released an implementation yet.

Its been a while since I have trained the model and I don't have access to it anymore. Sorry about that

**Comment by trungmanhhuynh** [comment]
Hi Anirudh, 

I just want to follow up with this discussion since your work is interesting to me. 
You said this is not official implementation so why the author refer your implementation in his website, 
you can find here: http://web.stanford.edu/~alahi/index.html#code 
I was guessing that you and the first author are on the same team, but it seems not. 

 I think there is no way that we can reproduce the results as in the paper, 
Anyway, thanks for sharing your work
